/* Zimmet Modülü — TO-BE dummy data.
   Personel LDAP'tan, stok/seri/irsaliye Logo ERP'den gelir. Manuel personel kaydı yok. */

window.ASSET_DB = (function () {
  const today = "2026-08-19";

  const roles = {
    support: {
      id: "u-sup",
      name: "Ayşe Demir",
      title: "Sistem Destek Uzmanı",
      dept: "Bilgi Teknolojileri",
      role: "support",
      roleLabel: "Sistem Destek Uzmanı",
    },
    warehouse: {
      id: "u-wh",
      name: "Kemal Uçar",
      title: "Depo Sorumlusu",
      dept: "Lojistik",
      role: "warehouse",
      roleLabel: "Depo Sorumlusu",
    },
    ceo: {
      id: "u-ceo",
      name: "Selim Aras",
      title: "Chief Operating Officer",
      dept: "Üst Yönetim",
      role: "ceo",
      roleLabel: "CO / CEO",
    },
    hr: {
      id: "u-hr",
      name: "Mehmet Kaya",
      title: "İK İşe Alım Uzmanı",
      dept: "İnsan Kaynakları",
      role: "hr",
      roleLabel: "İnsan Kaynakları",
    },
    admin: {
      id: "u-adm",
      name: "Burak Şahin",
      title: "Sistem Yöneticisi",
      dept: "Bilgi Teknolojileri",
      role: "admin",
      roleLabel: "Sistem Yöneticisi",
    },
    personnel: {
      id: "u-per",
      name: "Teslim Alan Personel",
      title: "Çalışan",
      dept: "—",
      role: "personnel",
      roleLabel: "Personel (Teslim Alan)",
    },
  };

  const employees = [
    {
      id: "e-ahmet",
      name: "Ahmet Yılmaz",
      sicil: "18440",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-24",
      leaveDate: null,
      email: "ahmet.yilmaz@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-elifd",
      name: "Elif Demir",
      sicil: "18441",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-25",
      leaveDate: null,
      email: "elif.demir@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-burak",
      name: "Burak Şen",
      sicil: "18442",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2026-08-26",
      leaveDate: null,
      email: "burak.sen@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-merve",
      name: "Merve Kılıç",
      sicil: "18435",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-20",
      leaveDate: null,
      email: "merve.kilic@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-ceren",
      name: "Ceren Uçar",
      sicil: "18433",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-19",
      leaveDate: null,
      email: "ceren.ucar@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-hakan",
      name: "Hakan Yılmaz",
      sicil: "18431",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-18",
      leaveDate: null,
      email: "hakan.yilmaz@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-ipek",
      name: "İpek Öz",
      sicil: "18429",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Genel Merkez",
      startDate: "2026-08-17",
      leaveDate: null,
      email: "ipek.oz@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-gokhan",
      name: "Gökhan Acar",
      sicil: "18422",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-08-10",
      leaveDate: null,
      email: "gokhan.acar@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-selin",
      name: "Selin Arslan",
      sicil: "16811",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2021-09-01",
      leaveDate: "2026-08-22",
      email: "selin.arslan@sirket.com",
      status: "offboarding",
      ldap: true,
    },
    {
      id: "e-can",
      name: "Can Özkan",
      sicil: "17204",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2023-03-12",
      leaveDate: "2026-08-21",
      email: "can.ozkan@sirket.com",
      status: "offboarding",
      ldap: true,
    },
    {
      id: "e-baran",
      name: "Baran Koç",
      sicil: "17655",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2024-01-08",
      leaveDate: null,
      email: "baran.koc@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-zeynep",
      name: "Zeynep Aksoy",
      sicil: "18102",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2025-02-03",
      leaveDate: null,
      email: "zeynep.aksoy@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-kaan",
      name: "Kaan Erdem",
      sicil: "17990",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2024-06-11",
      leaveDate: null,
      email: "kaan.erdem@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-mert",
      name: "Mert Çelik",
      sicil: "18428",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Ayşe Demir",
      location: "Genel Merkez",
      startDate: "2026-01-12",
      leaveDate: null,
      email: "mert.celik@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-nisa",
      name: "Nisa Kurt",
      sicil: "18044",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Genel Merkez",
      startDate: "2025-09-01",
      leaveDate: null,
      email: "nisa.kurt@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-tugce",
      name: "Tuğçe Aydın",
      sicil: "18445",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-09-01",
      leaveDate: null,
      email: "tugce.aydin@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-deniz",
      name: "Deniz Arslan",
      sicil: "18450",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-09-02",
      leaveDate: null,
      email: "deniz.arslan@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-ece",
      name: "Ece Yaman",
      sicil: "18451",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-09-03",
      leaveDate: null,
      email: "ece.yaman@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-onur",
      name: "Onur Kaya",
      sicil: "18452",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2026-09-04",
      leaveDate: null,
      email: "onur.kaya@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-seda",
      name: "Seda Polat",
      sicil: "18453",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2026-09-05",
      leaveDate: null,
      email: "seda.polat@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-emre",
      name: "Emre Taş",
      sicil: "18454",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Genel Merkez",
      startDate: "2026-09-08",
      leaveDate: null,
      email: "emre.tas@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-derya",
      name: "Derya Şimşek",
      sicil: "18455",
      dept: "Finans",
      title: "Software Developer",
      manager: "Ayşe Demir",
      location: "Genel Merkez",
      startDate: "2026-09-08",
      leaveDate: null,
      email: "derya.simsek@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-alp",
      name: "Alp Koçak",
      sicil: "18456",
      dept: "İnsan Kaynakları",
      title: "Sales Specialist",
      manager: "Mehmet Kaya",
      location: "Kartal",
      startDate: "2026-09-09",
      leaveDate: null,
      email: "alp.kocak@sirket.com",
      status: "onboarding",
      ldap: true,
    },
    {
      id: "e-melis",
      name: "Melis Uçar",
      sicil: "17501",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Kartal",
      startDate: "2024-04-15",
      leaveDate: null,
      email: "melis.ucar@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-okan",
      name: "Okan Demirtaş",
      sicil: "17320",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2023-11-06",
      leaveDate: null,
      email: "okan.demirtas@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-yasemin",
      name: "Yasemin Erol",
      sicil: "16988",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2022-02-14",
      leaveDate: null,
      email: "yasemin.erol@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-pinar",
      name: "Pınar Güneş",
      sicil: "18210",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2025-05-19",
      leaveDate: null,
      email: "pinar.gunes@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-tolga",
      name: "Tolga Aydın",
      sicil: "17840",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Genel Merkez",
      startDate: "2024-08-01",
      leaveDate: null,
      email: "tolga.aydin@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-buse",
      name: "Buse Karahan",
      sicil: "18155",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Kartal",
      startDate: "2025-01-13",
      leaveDate: null,
      email: "buse.karahan@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-furkan",
      name: "Furkan Özdemir",
      sicil: "17702",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Ayşe Demir",
      location: "Genel Merkez",
      startDate: "2024-03-04",
      leaveDate: null,
      email: "furkan.ozdemir@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-nazli",
      name: "Nazlı Çetin",
      sicil: "17418",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2023-09-18",
      leaveDate: null,
      email: "nazli.cetin@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-serkan",
      name: "Serkan Acar",
      sicil: "17090",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2022-06-27",
      leaveDate: null,
      email: "serkan.acar@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-aylin",
      name: "Aylin Koç",
      sicil: "18301",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2025-07-07",
      leaveDate: null,
      email: "aylin.koc@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-cem",
      name: "Cem Yalçın",
      sicil: "16640",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Kartal",
      startDate: "2021-04-12",
      leaveDate: null,
      email: "cem.yalcin@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-volkan",
      name: "Volkan Ersoy",
      sicil: "17112",
      dept: "Bilgi Teknolojileri",
      title: "Software Developer",
      manager: "Elif Yıldız",
      location: "Kartal",
      startDate: "2022-10-03",
      leaveDate: null,
      email: "volkan.ersoy@sirket.com",
      status: "active",
      ldap: true,
    },
    {
      id: "e-damla",
      name: "Damla Işık",
      sicil: "16502",
      dept: "Satış",
      title: "Sales Specialist",
      manager: "Hakan Polat",
      location: "Genel Merkez",
      startDate: "2020-11-09",
      leaveDate: "2026-08-28",
      email: "damla.isik@sirket.com",
      status: "offboarding",
      ldap: true,
    },
    {
      id: "e-koray",
      name: "Koray Şenel",
      sicil: "16777",
      dept: "Bilgi Teknolojileri",
      title: "Senior Software Developer",
      manager: "Elif Yıldız",
      location: "Genel Merkez",
      startDate: "2021-01-18",
      leaveDate: "2026-08-29",
      email: "koray.senel@sirket.com",
      status: "offboarding",
      ldap: true,
    },
  ];

  const packages = [
    {
      id: "pkg-ssd",
      name: "Senior Software Developer Paketi",
      title: "Senior Software Developer",
      description: "Geliştirici kıdem paketi — laptop, monitör ve çevre birimleri.",
      active: true,
      items: [
        { equipment: "Notebook", productCode: "NB-LNV-T14", qty: 1, note: "14 inç iş istasyonu" },
        { equipment: "Monitör", productCode: "MON-DEL-27", qty: 1, note: "USB-C 27 inç" },
        { equipment: "Mouse", productCode: "MS-LG-M650", qty: 1, note: "" },
        { equipment: "Klavye", productCode: "KB-LG-MX", qty: 1, note: "" },
        { equipment: "Adaptör", productCode: "ADP-LNV-65", qty: 1, note: "" },
        { equipment: "Çanta", productCode: "BAG-TARGUS", qty: 1, note: "" },
        { equipment: "Kulaklık", productCode: "HS-JABRA-65", qty: 1, note: "" },
      ],
    },
    {
      id: "pkg-dev",
      name: "Software Developer Paketi",
      title: "Software Developer",
      description: "Standart geliştirici paketi — monitör hariç.",
      active: true,
      items: [
        { equipment: "Notebook", productCode: "NB-LNV-T14", qty: 1, note: "" },
        { equipment: "Mouse", productCode: "MS-LG-M650", qty: 1, note: "" },
        { equipment: "Klavye", productCode: "KB-LG-MX", qty: 1, note: "" },
        { equipment: "Adaptör", productCode: "ADP-LNV-65", qty: 1, note: "" },
        { equipment: "Çanta", productCode: "BAG-TARGUS", qty: 1, note: "" },
        { equipment: "Kulaklık", productCode: "HS-JABRA-65", qty: 1, note: "" },
      ],
    },
    {
      id: "pkg-sales",
      name: "Sales Specialist Paketi",
      title: "Sales Specialist",
      description: "Saha satış paketi — laptop, telefon, headset.",
      active: true,
      items: [
        { equipment: "Notebook", productCode: "NB-LNV-T14", qty: 1, note: "" },
        { equipment: "Diğer", productCode: "PH-SM-A54", qty: 1, note: "Kurumsal hat" },
        { equipment: "Adaptör", productCode: "ADP-LNV-65", qty: 1, note: "" },
        { equipment: "Çanta", productCode: "BAG-TARGUS", qty: 1, note: "" },
        { equipment: "Kulaklık", productCode: "HS-JABRA-65", qty: 1, note: "" },
      ],
    },
  ];

  const logoCatalog = [
    {
      productCode: "NB-LNV-T14",
      stockCode: "LT-001",
      name: "Lenovo ThinkPad T14 Gen 4",
      brand: "Lenovo",
      model: "ThinkPad T14 Gen 4",
      equipment: "Notebook",
      assetType: "Notebook",
      productGroup: "Bilgisayar",
      cost: 42500,
      description: "14 inç / i7 / 16GB / 512GB",
      warehouse: "IT Deposu",
      qty: 12,
      serials: ["SN123456", "SN123457", "SN123458", "SN123459", "SN123460", "SN123461", "SN123470", "LNV-T14-88101", "LNV-T14-88102"],
    },
    {
      productCode: "NB-HP-840",
      stockCode: "LT-002",
      name: "HP EliteBook 840 G10",
      brand: "HP",
      model: "EliteBook 840 G10",
      equipment: "Notebook",
      assetType: "Notebook",
      productGroup: "Bilgisayar",
      cost: 38900,
      description: "14 inç / i7 / 16GB / 512GB",
      warehouse: "IT Deposu",
      qty: 3,
      serials: ["HP-840-11820", "HP-840-11821", "HP-840-11822"],
    },
    {
      productCode: "NB-MAC-PRO",
      stockCode: "MB-001",
      name: "Apple MacBook Pro 14 M3",
      brand: "Apple",
      model: "MacBook Pro 14 M3",
      equipment: "Notebook",
      assetType: "Notebook",
      productGroup: "Bilgisayar",
      cost: 78500,
      description: "14 inç / M3 / 16GB / 512GB",
      warehouse: "IT Deposu",
      qty: 0,
      serials: [],
    },
    {
      productCode: "MON-DEL-27",
      stockCode: "MN-001",
      name: "Dell P2723DE 27 inç USB-C Monitör",
      brand: "Dell",
      model: "P2723DE",
      equipment: "Monitör",
      assetType: "Monitör",
      productGroup: "Görüntü",
      cost: 12400,
      description: "27 inç QHD USB-C",
      warehouse: "IT Deposu",
      qty: 5,
      serials: ["DELL-P27-33811", "DELL-P27-33812", "DELL-P27-33813", "DELL-P27-44120", "DELL-P27-55201"],
    },
    {
      productCode: "MON-LG-34",
      stockCode: "MN-002",
      name: "LG UltraWide 34WP65C",
      brand: "LG",
      model: "34WP65C",
      equipment: "Monitör",
      assetType: "Monitör",
      productGroup: "Görüntü",
      cost: 16800,
      description: "34 inç ultrawide",
      warehouse: "IT Deposu",
      qty: 2,
      serials: ["LG-34-4411", "LG-34-4412"],
    },
    {
      productCode: "MS-LG-M650",
      stockCode: "MS-001",
      name: "Logitech MX Master 3S",
      brand: "Logitech",
      model: "MX Master 3S",
      equipment: "Mouse",
      assetType: "Çevre Birimi",
      productGroup: "Çevre Birimi",
      cost: 3200,
      description: "Kablosuz ergonomik mouse",
      warehouse: "IT Deposu",
      qty: 20,
      serials: ["LG-MX3S-2201", "LG-MX3S-2202", "LG-MX3S-4419", "LG-MX3S-5510", "LG-MX3S-5511"],
    },
    {
      productCode: "KB-LG-MX",
      stockCode: "KB-001",
      name: "Logitech MX Keys",
      brand: "Logitech",
      model: "MX Keys",
      equipment: "Klavye",
      assetType: "Çevre Birimi",
      productGroup: "Çevre Birimi",
      cost: 2800,
      description: "Kablosuz klavye",
      warehouse: "IT Deposu",
      qty: 15,
      serials: ["LG-MXK-1001", "LG-MXK-1002", "LG-MXK-1003", "LG-MXK-1004"],
    },
    {
      productCode: "HS-JABRA-65",
      stockCode: "HS-001",
      name: "Jabra Evolve2 65",
      brand: "Jabra",
      model: "Evolve2 65",
      equipment: "Kulaklık",
      assetType: "Çevre Birimi",
      productGroup: "Çevre Birimi",
      cost: 4100,
      description: "Bluetooth kulaklık",
      warehouse: "IT Deposu",
      qty: 8,
      serials: ["JB-E265-4401", "JB-E265-4402", "JB-E265-4403", "JB-E265-4404", "JB-E265-4410", "JB-E265-4422"],
    },
    {
      productCode: "PH-SM-A54",
      stockCode: "PH-001",
      name: "Samsung Galaxy A54",
      brand: "Samsung",
      model: "Galaxy A54",
      equipment: "Diğer",
      assetType: "Mobil",
      productGroup: "Mobil",
      cost: 18500,
      description: "Kurumsal cep telefonu",
      warehouse: "IT Deposu",
      qty: 4,
      serials: ["SM-A546B-9912", "SM-A546B-9913", "SM-A546B-9914", "SM-A546B-9920", "SM-A546B-9931"],
    },
    {
      productCode: "DOCK-DELL-WD19",
      stockCode: "DK-001",
      name: "Dell WD19S USB-C Dock",
      brand: "Dell",
      model: "WD19S",
      equipment: "Dock Station",
      assetType: "Dock Station",
      productGroup: "Çevre Birimi",
      cost: 5400,
      description: "USB-C docking station",
      warehouse: "IT Deposu",
      qty: 4,
      serials: ["DELL-WD19-2208", "DELL-WD19-2209", "DELL-WD19-2210"],
    },
    {
      productCode: "ADP-LNV-65",
      stockCode: "AD-001",
      name: "Lenovo 65W USB-C Adaptör",
      brand: "Lenovo",
      model: "65W USB-C",
      equipment: "Adaptör",
      assetType: "Çevre Birimi",
      productGroup: "Aksesuar",
      cost: 890,
      description: "Standart notebook adaptörü",
      warehouse: "IT Deposu",
      qty: 18,
      serials: ["ADP-65-1001", "ADP-65-1002", "ADP-65-1003"],
    },
    {
      productCode: "BAG-TARGUS",
      stockCode: "BG-001",
      name: "Targus 14 inç Notebook Çantası",
      brand: "Targus",
      model: "TBB641",
      equipment: "Çanta",
      assetType: "Çevre Birimi",
      productGroup: "Aksesuar",
      cost: 1450,
      description: "14 inç korumalı çanta",
      warehouse: "IT Deposu",
      qty: 9,
      serials: ["TG-BAG-2201", "TG-BAG-2202"],
    },
  ];

  const warehouses = [
    { id: "wh-it", name: "IT Deposu", city: "İstanbul", address: "Cevizli Mah. Tugay Yolu Cad. No: 12", district: "Kartal / İstanbul", phone: "0216 555 01 10" },
    { id: "wh-gm", name: "Merkez Depo", city: "İstanbul", address: "Büyükdere Cad. No: 185", district: "Şişli / İstanbul", phone: "0212 555 01 20" },
    { id: "wh-kartal", name: "Kartal Ofis", city: "İstanbul", address: "Cevizli Mah. Tugay Yolu Cad. No: 12", district: "Kartal / İstanbul", phone: "0216 555 01 10" },
  ];

  function item(partial) {
    return Object.assign(
      {
        id: null,
        equipment: "",
        productCode: "",
        name: "",
        stockCode: "",
        qty: 1,
        inPackage: true,
        stockStatus: "stokta",
        stockQty: 0,
        warehouse: "IT Deposu",
        serial: null,
        extra: false,
        extraReason: "",
        alternativeOf: null,
        returnCondition: null,
        returnChecks: { model: false, serial: false, accessory: false, damage: false },
        returnNote: "",
      },
      partial
    );
  }

  const jobs = [
    {
      id: "job-onb-001",
      no: "IB-2026-0018",
      process: "ise-baslangic",
      employeeId: "e-ahmet",
      packageId: "pkg-ssd",
      status: "sistem-destek-kontrolunde",
      location: "Genel Merkez",
      createdAt: "2026-08-19 09:12",
      createdBy: "Mehmet Kaya",
      startDate: "2026-08-24",
      deliveryDate: "2026-08-22",
      slaDays: 3,
      slaDue: "2026-08-22",
      slaStatus: "ok",
      approver: "Ayşe Demir",
      supportNote: "",
      ceoNote: "",
      ceoDecision: null,
      waybill: null,
      waybillDate: null,
      waybillTarget: "Genel Merkez",
      formNo: null,
      signMethod: null,
      needsCeo: false,
      history: [
        { t: "2026-08-19 09:12", who: "Ayşe Demir", ev: "LDAP'tan personel seçildi", note: "Ahmet Yılmaz · Senior Software Developer" },
        { t: "2026-08-19 09:12", who: "Sistem", ev: "Ekipman paketi otomatik getirildi", note: "Senior Software Developer Paketi" },
        { t: "2026-08-19 09:13", who: "Ayşe Demir", ev: "Cihaz zimmeti oluşturuldu", note: "Sistem Destek kontrolüne düştü" },
      ],
      items: [
        item({ id: "i-a1", equipment: "Laptop", productCode: "NB-MAC-PRO", name: "Apple MacBook Pro 14 M3", stockCode: "MB-001", inPackage: false, stockStatus: "yok", stockQty: 0, extra: true, extraReason: "Personel macOS geliştirme ortamı talep etti. Pakette ThinkPad var." }),
        item({ id: "i-a2", equipment: "Monitör", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", stockCode: "MN-001", stockStatus: "stokta", stockQty: 5 }),
        item({ id: "i-a3", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", stockStatus: "stokta", stockQty: 20 }),
        item({ id: "i-a4", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", stockStatus: "stokta", stockQty: 15 }),
        item({ id: "i-a5", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", stockStatus: "stokta", stockQty: 8 }),
      ],
    },
    {
      id: "job-onb-002",
      no: "IB-2026-0016",
      process: "ise-baslangic",
      employeeId: "e-elifd",
      packageId: "pkg-dev",
      status: "ceo-onayi-bekliyor",
      location: "Genel Merkez",
      createdAt: "2026-08-18 14:40",
      createdBy: "Mehmet Kaya",
      startDate: "2026-08-25",
      deliveryDate: "2026-08-23",
      slaDays: 3,
      slaDue: "2026-08-21",
      slaStatus: "risk",
      approver: "Selim Aras",
      reminderCount: 1,
      supportNote: "Geliştirici paketine 2. monitör ve dock eklendi. macOS yok; standart ThinkPad duruyor.",
      approvalHistory: [
        { step: "Sistem Destek Kontrolü", who: "Ayşe Demir", result: "Onaya gönderildi", t: "2026-08-18 15:02", note: "Paket dışı monitör + dock" },
        { step: "CO / CEO Onayı", who: "Selim Aras", result: "Bekliyor", t: "", note: "SLA 3 iş günü · 1. gün hatırlatması gönderildi" },
      ],
      ceoNote: "",
      ceoDecision: null,
      waybill: null,
      waybillDate: null,
      waybillTarget: "Genel Merkez",
      formNo: null,
      signMethod: null,
      needsCeo: true,
      history: [
        { t: "2026-08-18 14:40", who: "Ayşe Demir", ev: "LDAP personel seçildi" },
        { t: "2026-08-18 14:41", who: "Sistem", ev: "Software Developer paketi getirildi" },
        { t: "2026-08-18 15:02", who: "Ayşe Demir", ev: "Paket dışı ekipman eklendi", note: "2. monitör + dock — CO/CEO onayına gönderildi" },
      ],
      items: [
        item({ id: "i-b1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", stockStatus: "stokta", stockQty: 12 }),
        item({ id: "i-b2", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", stockStatus: "stokta", stockQty: 20 }),
        item({ id: "i-b3", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", stockStatus: "stokta", stockQty: 15 }),
        item({ id: "i-b4", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", stockStatus: "stokta", stockQty: 8 }),
        item({ id: "i-b5", equipment: "Monitör", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", stockCode: "MN-001", inPackage: false, extra: true, extraReason: "Çift ekran geliştirme talebi. Developer paketinde monitör yok.", stockStatus: "stokta", stockQty: 5 }),
        item({ id: "i-b6", equipment: "Dock", productCode: "DOCK-DELL-WD19", name: "Dell WD19S USB-C Dock", stockCode: "DK-001", inPackage: false, extra: true, extraReason: "Çift monitör için dock gerekli.", stockStatus: "stokta", stockQty: 4 }),
      ],
    },
    {
      id: "job-onb-003",
      no: "IB-2026-0014",
      process: "ise-baslangic",
      employeeId: "e-burak",
      packageId: "pkg-sales",
      status: "depo-hazirliginda",
      location: "Kartal",
      createdAt: "2026-08-18 11:05",
      createdBy: "Mehmet Kaya",
      startDate: "2026-08-26",
      deliveryDate: "2026-08-25",
      slaDays: 3,
      slaDue: "2026-08-21",
      slaStatus: "ok",
      approver: "Kemal Uçar",
      supportNote: "Satış paketi standart. Onay gerekmedi.",
      ceoNote: "",
      ceoDecision: null,
      waybill: null,
      waybillDate: null,
      waybillTarget: "Kartal Ofis",
      formNo: null,
      signMethod: null,
      needsCeo: false,
      history: [
        { t: "2026-08-18 11:05", who: "Ayşe Demir", ev: "Cihaz zimmeti oluşturuldu" },
        { t: "2026-08-18 11:40", who: "Ayşe Demir", ev: "Sistem Destek kontrolü tamamlandı", note: "Paket dahil — depo sürecine gönderildi" },
      ],
      items: [
        item({ id: "i-c1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", stockStatus: "stokta", stockQty: 12, serial: null }),
        item({ id: "i-c2", equipment: "Telefon", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", stockCode: "PH-001", stockStatus: "stokta", stockQty: 4, serial: null }),
        item({ id: "i-c3", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", stockStatus: "stokta", stockQty: 8, serial: null }),
      ],
    },
    {
      id: "job-onb-004",
      no: "IB-2026-0012",
      process: "ise-baslangic",
      employeeId: "e-merve",
      packageId: "pkg-ssd",
      status: "seri-secildi",
      location: "Genel Merkez",
      createdAt: "2026-08-17 16:20",
      createdBy: "Ayşe Demir",
      supportNote: "Standart kıdem paketi.",
      waybill: null,
      waybillDate: null,
      waybillTarget: "Genel Merkez",
      formNo: null,
      needsCeo: false,
      history: [
        { t: "2026-08-17 16:20", who: "Ayşe Demir", ev: "Cihaz zimmeti oluşturuldu" },
        { t: "2026-08-18 09:10", who: "Ayşe Demir", ev: "Sistem Destek kontrolü tamamlandı" },
        { t: "2026-08-19 08:44", who: "Kemal Uçar", ev: "Tüm seri numaraları seçildi", note: "Logo ERP stok" },
      ],
      items: [
        item({ id: "i-d1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "SN123456", stockStatus: "stokta", stockQty: 12 }),
        item({ id: "i-d2", equipment: "Monitör", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", stockCode: "MN-001", serial: "DELL-P27-33811", stockStatus: "stokta", stockQty: 5 }),
        item({ id: "i-d3", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", serial: "LG-MX3S-2201", stockStatus: "stokta", stockQty: 20 }),
        item({ id: "i-d4", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", serial: "LG-MXK-1001", stockStatus: "stokta", stockQty: 15 }),
        item({ id: "i-d5", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-4401", stockStatus: "stokta", stockQty: 8 }),
      ],
    },
    {
      id: "job-onb-005",
      no: "IB-2026-0010",
      process: "ise-baslangic",
      employeeId: "e-ceren",
      packageId: "pkg-dev",
      status: "merkeze-ulasti",
      location: "Genel Merkez",
      createdAt: "2026-08-16 10:00",
      createdBy: "Ayşe Demir",
      waybill: "IRS-2026-1188",
      waybillDate: "2026-08-18 16:10",
      waybillTarget: "Genel Merkez",
      formNo: null,
      needsCeo: false,
      history: [
        { t: "2026-08-16 10:00", who: "Ayşe Demir", ev: "Cihaz zimmeti oluşturuldu" },
        { t: "2026-08-17 11:20", who: "Kemal Uçar", ev: "Sevk irsaliyesi oluşturuldu", note: "Logo ERP · IRS-2026-1188" },
        { t: "2026-08-19 08:15", who: "Sistem", ev: "Ekipmanlar merkeze ulaştı", note: "Sistem Destek Uzmanına bildirim" },
      ],
      items: [
        item({ id: "i-e1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "SN123457", stockStatus: "stokta", stockQty: 12 }),
        item({ id: "i-e2", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", serial: "LG-MX3S-2202", stockStatus: "stokta", stockQty: 20 }),
        item({ id: "i-e3", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", serial: "LG-MXK-1002", stockStatus: "stokta", stockQty: 15 }),
        item({ id: "i-e4", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-4402", stockStatus: "stokta", stockQty: 8 }),
      ],
    },
    {
      id: "job-onb-006",
      no: "IB-2026-0008",
      process: "ise-baslangic",
      employeeId: "e-hakan",
      packageId: "pkg-ssd",
      status: "teknik-kontrol-bekliyor",
      location: "Genel Merkez",
      createdAt: "2026-08-15 09:30",
      createdBy: "Ayşe Demir",
      waybill: "IRS-2026-1174",
      waybillDate: "2026-08-16 14:00",
      waybillTarget: "Genel Merkez",
      formNo: null,
      needsCeo: false,
      checks: {
        physical: [
          { id: "p1", label: "Cihaz modeli doğrulandı", done: true },
          { id: "p2", label: "Seri numarası doğrulandı", done: true },
          { id: "p3", label: "Fiziksel durum uygun", done: false },
          { id: "p4", label: "Aksesuarlar tam", done: false },
          { id: "p5", label: "Hasar yok", done: false },
        ],
        technical: [
          { id: "t1", label: "İşletim sistemi kurulumu", done: false },
          { id: "t2", label: "Yazılım kurulumu", done: false },
          { id: "t3", label: "Gerekli uygulamalar", done: false },
          { id: "t4", label: "Kullanıcı hesabı", done: false },
          { id: "t5", label: "Cihaz kurulumu tamam", done: false },
        ],
      },
      history: [
        { t: "2026-08-18 09:00", who: "Ayşe Demir", ev: "Merkez teslim alındı" },
        { t: "2026-08-19 09:20", who: "Ayşe Demir", ev: "Teknik / fiziksel kontrole alındı" },
      ],
      items: [
        item({ id: "i-f1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "SN123458" }),
        item({ id: "i-f2", equipment: "Monitör", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", stockCode: "MN-001", serial: "DELL-P27-33812" }),
        item({ id: "i-f3", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", serial: "LG-MX3S-4419" }),
        item({ id: "i-f4", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", serial: "LG-MXK-1003" }),
        item({ id: "i-f5", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-4403" }),
      ],
    },
    {
      id: "job-onb-007",
      no: "IB-2026-0006",
      process: "ise-baslangic",
      employeeId: "e-ipek",
      packageId: "pkg-sales",
      status: "zimmet-formu-bekliyor",
      location: "Genel Merkez",
      createdAt: "2026-08-14 11:00",
      createdBy: "Ayşe Demir",
      waybill: "IRS-2026-1160",
      waybillDate: "2026-08-15 10:22",
      waybillTarget: "Genel Merkez",
      formNo: null,
      needsCeo: false,
      checks: {
        physical: [
          { id: "p1", label: "Cihaz modeli doğrulandı", done: true },
          { id: "p2", label: "Seri numarası doğrulandı", done: true },
          { id: "p3", label: "Fiziksel durum uygun", done: true },
          { id: "p4", label: "Aksesuarlar tam", done: true },
          { id: "p5", label: "Hasar yok", done: true },
        ],
        technical: [
          { id: "t1", label: "İşletim sistemi kurulumu", done: true },
          { id: "t2", label: "Yazılım kurulumu", done: true },
          { id: "t3", label: "Gerekli uygulamalar", done: true },
          { id: "t4", label: "Kullanıcı hesabı", done: true },
          { id: "t5", label: "Cihaz kurulumu tamam", done: true },
        ],
      },
      history: [
        { t: "2026-08-18 16:40", who: "Ayşe Demir", ev: "Teknik ve fiziksel kontrol tamamlandı" },
      ],
      items: [
        item({ id: "i-g1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "SN123459" }),
        item({ id: "i-g2", equipment: "Telefon", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", stockCode: "PH-001", serial: "SM-A546B-9913" }),
        item({ id: "i-g3", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-4404" }),
      ],
    },
    {
      id: "job-onb-008",
      no: "IB-2026-0002",
      process: "ise-baslangic",
      employeeId: "e-gokhan",
      packageId: "pkg-dev",
      status: "tamamlandi",
      location: "Genel Merkez",
      createdAt: "2026-08-08 10:00",
      createdBy: "Ayşe Demir",
      waybill: "IRS-2026-1102",
      waybillDate: "2026-08-09 09:00",
      waybillTarget: "Genel Merkez",
      formNo: "ZM-2026-0208",
      signMethod: "dijital-imza",
      signedAt: "2026-08-10 11:18",
      needsCeo: false,
      history: [
        { t: "2026-08-10 11:18", who: "Gökhan Acar", ev: "Dijital imza tamamlandı" },
        { t: "2026-08-10 11:18", who: "Sistem", ev: "Zimmet kaydı aktif" },
      ],
      items: [
        item({ id: "i-h1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "LNV-T14-77001" }),
        item({ id: "i-h2", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", serial: "LG-MX3S-77002" }),
        item({ id: "i-h3", equipment: "Keyboard", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", serial: "LG-MXK-77003" }),
        item({ id: "i-h4", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-77004" }),
      ],
    },
    {
      id: "job-off-001",
      no: "IA-2026-0044",
      process: "isten-ayrilis",
      employeeId: "e-selin",
      packageId: "pkg-sales",
      status: "isten-ayrilis-bekliyor",
      location: "Kartal",
      createdAt: "2026-08-19 08:05",
      createdBy: "Mehmet Kaya",
      waybill: null,
      waybillDate: null,
      waybillTarget: "Merkez Depo",
      formNo: "ZM-2025-2218",
      needsCeo: false,
      history: [
        { t: "2026-08-19 08:05", who: "Mehmet Kaya", ev: "İK işten ayrılış kaydı oluşturdu", note: "Son gün 22.08.2026" },
        { t: "2026-08-19 08:05", who: "Sistem", ev: "Sistem Destek Uzmanına bildirim", note: "4 zimmetli ürünün iadesi bekleniyor" },
      ],
      items: [
        item({ id: "i-s1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "LNV-T14-441902" }),
        item({ id: "i-s2", equipment: "Telefon", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", stockCode: "PH-001", serial: "SM-A546B-9912" }),
        item({ id: "i-s3", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-1188" }),
        item({ id: "i-s4", equipment: "Mouse", productCode: "MS-LG-M650", name: "Logitech MX Master 3S", stockCode: "MS-001", serial: "LG-MX3S-1844", inPackage: false }),
      ],
    },
    {
      id: "job-off-002",
      no: "IA-2026-0042",
      process: "isten-ayrilis",
      employeeId: "e-can",
      packageId: "pkg-dev",
      status: "iade-kontrolunde",
      location: "Genel Merkez",
      createdAt: "2026-08-18 10:00",
      createdBy: "Mehmet Kaya",
      waybill: null,
      waybillTarget: "Merkez Depo",
      formNo: "ZM-2026-0142",
      needsCeo: false,
      history: [
        { t: "2026-08-18 10:00", who: "Mehmet Kaya", ev: "İK işten ayrılış kaydı" },
        { t: "2026-08-19 09:00", who: "Ayşe Demir", ev: "İade kontrolüne alındı" },
      ],
      items: [
        item({
          id: "i-o1",
          equipment: "Laptop",
          productCode: "NB-LNV-T14",
          name: "Lenovo ThinkPad T14 Gen 4",
          stockCode: "LT-001",
          serial: "HM4-14-771002",
          returnCondition: "yeniden",
          returnChecks: { model: true, serial: true, accessory: true, damage: false },
          returnNote: "Kasa köşesinde hafif çizik.",
        }),
        item({
          id: "i-o2",
          equipment: "Mouse",
          productCode: "MS-LG-M650",
          name: "Logitech MX Master 3S",
          stockCode: "MS-001",
          serial: "LG-MX3S-3001",
          returnCondition: null,
          returnChecks: { model: false, serial: false, accessory: false, damage: false },
        }),
        item({
          id: "i-o3",
          equipment: "Keyboard",
          productCode: "KB-LG-MX",
          name: "Logitech MX Keys",
          stockCode: "KB-001",
          serial: "LG-MXK-3002",
          returnCondition: null,
          returnChecks: { model: false, serial: false, accessory: false, damage: false },
        }),
        item({
          id: "i-o4",
          equipment: "Headset",
          productCode: "HS-JABRA-65",
          name: "Jabra Evolve2 65",
          stockCode: "HS-001",
          serial: "JB-E265-3003",
          returnCondition: null,
          returnChecks: { model: false, serial: false, accessory: false, damage: false },
        }),
      ],
    },
    {
      id: "job-off-003",
      no: "IA-2026-0038",
      process: "isten-ayrilis",
      employeeId: "e-nisa",
      packageId: "pkg-sales",
      status: "iade-tamamlandi",
      location: "Genel Merkez",
      createdAt: "2026-08-12 09:00",
      createdBy: "Mehmet Kaya",
      waybill: null,
      waybillTarget: "Merkez Depo",
      formNo: "ZM-2025-1880",
      needsCeo: false,
      history: [
        { t: "2026-08-18 17:10", who: "Ayşe Demir", ev: "İade kontrolü tamamlandı", note: "Laptop yeniden kullanıma uygun" },
      ],
      items: [
        item({ id: "i-n1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "LNV-T14-18801", returnCondition: "yeniden" }),
        item({ id: "i-n2", equipment: "Telefon", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", stockCode: "PH-001", serial: "SM-A546B-18802", returnCondition: "bakim" }),
        item({ id: "i-n3", equipment: "Headset", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", stockCode: "HS-001", serial: "JB-E265-18803", returnCondition: "hurda" }),
      ],
    },
    {
      id: "job-tr-001",
      no: "DV-2026-0011",
      process: "zimmet-devri",
      employeeId: "e-baran",
      toEmployeeId: "e-zeynep",
      packageId: "pkg-ssd",
      status: "yeni-kullanici-bekliyor",
      location: "Genel Merkez",
      createdAt: "2026-08-19 10:05",
      createdBy: "Ayşe Demir",
      formNo: null,
      needsCeo: false,
      sameLocation: true,
      history: [
        { t: "2026-08-19 10:05", who: "Ayşe Demir", ev: "Zimmet devri başlatıldı", note: "Baran Koç → hedef kullanıcı seçilecek" },
        { t: "2026-08-19 10:05", who: "Sistem", ev: "Lokasyon kontrolü", note: "Aynı lokasyon — ürün sistemde bulunabilir" },
      ],
      items: [
        item({ id: "i-t1", equipment: "Laptop", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "LNV-T14-300188" }),
      ],
    },
    {
      id: "job-tr-002",
      no: "DV-2026-0007",
      process: "zimmet-devri",
      employeeId: "e-baran",
      toEmployeeId: "e-kaan",
      packageId: "pkg-ssd",
      status: "lokasyon-uyusmazligi",
      location: "Genel Merkez",
      createdAt: "2026-08-18 13:20",
      createdBy: "Ayşe Demir",
      formNo: null,
      needsCeo: false,
      sameLocation: false,
      history: [
        { t: "2026-08-18 13:20", who: "Ayşe Demir", ev: "Devir denendi", note: "Kaan Erdem Kartal lokasyonunda" },
        { t: "2026-08-18 13:20", who: "Sistem", ev: "Lokasyon uyuşmazlığı", note: "Genel Merkez ≠ Kartal — ürün sistemde bulunamaz varsayımı" },
      ],
      items: [
        item({ id: "i-t2", equipment: "Monitör", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", stockCode: "MN-001", serial: "DELL-P27-300189" }),
      ],
    },
    {
      id: "job-ch-001",
      no: "DG-2026-0009",
      process: "cihaz-degisimi",
      employeeId: "e-mert",
      packageId: "pkg-dev",
      status: "sistem-destek-kontrolunde",
      location: "Genel Merkez",
      createdAt: "2026-08-19 09:40",
      createdBy: "Mert Çelik",
      supportNote: "",
      changeReason: "Mevcut ThinkPad fan arızası. Değişim talep edildi.",
      requestedEquipment: "Apple MacBook Pro 14 M3",
      requestedCode: "NB-MAC-PRO",
      inPackageCheck: false,
      needsCeo: true,
      waybill: null,
      history: [
        { t: "2026-08-19 09:40", who: "Mert Çelik", ev: "Cihaz değişim talebi oluşturuldu" },
        { t: "2026-08-19 09:41", who: "Sistem", ev: "Paket kontrolü", note: "MacBook Pro — paket dışı, CO/CEO onayı gerekir" },
      ],
      items: [
        item({ id: "i-ch1", equipment: "Laptop (mevcut)", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", serial: "LNV-T14-552881", inPackage: true }),
        item({ id: "i-ch2", equipment: "Laptop (talep)", productCode: "NB-MAC-PRO", name: "Apple MacBook Pro 14 M3", stockCode: "MB-001", inPackage: false, extra: true, extraReason: "Software Developer paketinde MacBook yok.", stockStatus: "yok", stockQty: 0 }),
      ],
    },
    {
      id: "job-ch-002",
      no: "DG-2026-0007",
      process: "cihaz-degisimi",
      employeeId: "e-zeynep",
      packageId: "pkg-dev",
      status: "depo-hazirliginda",
      location: "Genel Merkez",
      createdAt: "2026-08-18 15:10",
      createdBy: "Zeynep Aksoy",
      changeReason: "Klavye tuş arızası. Aynı model değişim.",
      requestedEquipment: "Logitech MX Keys",
      requestedCode: "KB-LG-MX",
      inPackageCheck: true,
      needsCeo: false,
      waybill: null,
      history: [
        { t: "2026-08-18 15:10", who: "Zeynep Aksoy", ev: "Cihaz değişim talebi" },
        { t: "2026-08-18 16:00", who: "Ayşe Demir", ev: "Paket dahilinde doğrulandı", note: "CO/CEO onayı gerekmedi — depoya iletildi" },
      ],
      items: [
        item({ id: "i-ch3", equipment: "Keyboard (mevcut)", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", serial: "LG-MXK-5519", inPackage: true }),
        item({ id: "i-ch4", equipment: "Klavye (yeni)", productCode: "KB-LG-MX", name: "Logitech MX Keys", stockCode: "KB-001", inPackage: true, stockStatus: "stokta", stockQty: 15, serial: null }),
      ],
    },
    {
      id: "job-onb-009",
      no: "IB-2026-0020",
      process: "ise-baslangic",
      employeeId: "e-tugce",
      packageId: "pkg-ssd",
      status: "taslak",
      location: "Genel Merkez",
      createdAt: "2026-08-19 14:20",
      createdBy: "Mehmet Kaya",
      startDate: "2026-09-01",
      deliveryDate: "",
      slaDays: 3,
      slaDue: "2026-08-22",
      slaStatus: "ok",
      supportNote: "",
      needsCeo: false,
      history: [
        { t: "2026-08-19 14:20", who: "Mehmet Kaya", ev: "Taslak talep oluşturuldu", note: "Cihaz teslim tarihi henüz seçilmedi" },
      ],
      items: [
        item({ id: "i-tg1", equipment: "Notebook", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", stockCode: "LT-001", stockStatus: "stokta", stockQty: 12 }),
      ],
    },
  ];

  const assets = [
    { id: "as-001", no: "AST-10442", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "LNV-T14-77001", warehouse: "—", location: "Genel Merkez", status: "Assigned", employeeId: "e-gokhan", cost: 42500, history: [
      { t: "2026-08-08 10:00", who: "Ayşe Demir", ev: "In Stock → Reserved", note: "Gökhan Acar işe başlangıç" },
      { t: "2026-08-09 09:00", who: "Kemal Uçar", ev: "Reserved → In Transfer", note: "IRS-2026-1102" },
      { t: "2026-08-10 09:40", who: "Ayşe Demir", ev: "In Transfer → Ready For Assignment", note: "Teknik kontrol uygun" },
      { t: "2026-08-10 11:18", who: "Ayşe Demir", ev: "Ready For Assignment → Assigned", note: "ZM-2026-0208" },
    ]},
    { id: "as-002", no: "AST-10418", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "SN123456", warehouse: "IT Deposu", location: "Kartal", status: "Reserved", employeeId: "e-merve", cost: 42500, history: [
      { t: "2026-08-19 08:44", who: "Kemal Uçar", ev: "In Stock → Reserved", note: "Merve Kılıç için ayrıldı" },
    ]},
    { id: "as-003", no: "AST-10390", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "SN123457", warehouse: "IT Deposu", location: "Genel Merkez", status: "In Transfer", employeeId: "e-ceren", cost: 42500, history: [
      { t: "2026-08-18 16:10", who: "Kemal Uçar", ev: "Reserved → In Transfer", note: "IRS-2026-1188" },
    ]},
    { id: "as-004", no: "AST-10355", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "SN123458", warehouse: "Merkez Depo", location: "Genel Merkez", status: "Ready For Assignment", employeeId: "e-hakan", cost: 42500, history: [
      { t: "2026-08-19 09:20", who: "Ayşe Demir", ev: "In Transfer → Ready For Assignment", note: "Teslim alındı, teknik kontrolde" },
    ]},
    { id: "as-005", no: "AST-10280", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "LNV-T14-441902", warehouse: "—", location: "Kartal", status: "Assigned", employeeId: "e-selin", cost: 42500, history: [] },
    { id: "as-006", no: "AST-10112", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "HM4-14-771002", warehouse: "—", location: "Genel Merkez", status: "Assigned", employeeId: "e-can", cost: 42500, history: [] },
    { id: "as-007", no: "AST-10088", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "LNV-T14-18801", warehouse: "Merkez Depo", location: "Genel Merkez", status: "Returned", employeeId: "e-nisa", cost: 42500, history: [
      { t: "2026-08-18 17:10", who: "Ayşe Demir", ev: "Assigned → Returned", note: "İşten ayrılış iadesi" },
    ]},
    { id: "as-008", no: "AST-09940", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", brand: "Samsung", model: "Galaxy A54", serial: "SM-A546B-18802", warehouse: "IT Deposu", location: "Genel Merkez", status: "Maintenance", employeeId: null, cost: 18500, history: [
      { t: "2026-08-18 17:12", who: "Ayşe Demir", ev: "Returned → Maintenance", note: "Ekran değişimi" },
    ]},
    { id: "as-009", no: "AST-09811", productCode: "HS-JABRA-65", name: "Jabra Evolve2 65", brand: "Jabra", model: "Evolve2 65", serial: "JB-E265-18803", warehouse: "Hurda Depo", location: "Genel Merkez", status: "Retired", employeeId: null, cost: 4100, history: [
      { t: "2026-08-18 17:14", who: "Ayşe Demir", ev: "Returned → Retired", note: "Hoparlör arızalı · Logo hurda depo" },
    ]},
    { id: "as-010", no: "AST-09702", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "LNV-T14-300188", warehouse: "—", location: "Genel Merkez", status: "Assigned", employeeId: "e-baran", cost: 42500, history: [] },
    { id: "as-011", no: "AST-09640", productCode: "NB-HP-840", name: "HP EliteBook 840 G10", brand: "HP", model: "EliteBook 840 G10", serial: "HP-840-11820", warehouse: "IT Deposu", location: "Kartal", status: "In Stock", employeeId: null, cost: 38900, history: [] },
    { id: "as-012", no: "AST-09501", productCode: "MON-DEL-27", name: "Dell P2723DE 27 inç USB-C Monitör", brand: "Dell", model: "P2723DE", serial: "DELL-P27-55201", warehouse: "IT Deposu", location: "Kartal", status: "Ready For Reassignment", employeeId: null, cost: 12400, history: [
      { t: "2026-08-12 14:00", who: "Ayşe Demir", ev: "Returned → Ready For Reassignment", note: "Yeniden kullanıma uygun" },
    ]},
    { id: "as-013", no: "AST-09420", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "LNV-T14-LOST1", warehouse: "—", location: "Genel Merkez", status: "Lost", employeeId: "e-mert", cost: 42500, history: [
      { t: "2026-07-02 11:00", who: "Ayşe Demir", ev: "Assigned → Lost", note: "Kayıp bildirimi" },
    ]},
    { id: "as-014", no: "AST-09311", productCode: "PH-SM-A54", name: "Samsung Galaxy A54", brand: "Samsung", model: "Galaxy A54", serial: "SM-A546B-STOL", warehouse: "—", location: "Kartal", status: "Stolen", employeeId: "e-kaan", cost: 18500, history: [
      { t: "2026-06-18 16:40", who: "Ayşe Demir", ev: "Assigned → Stolen", note: "Çalıntı bildirimi" },
    ]},
    { id: "as-015", no: "AST-10480", productCode: "NB-LNV-T14", name: "Lenovo ThinkPad T14 Gen 4", brand: "Lenovo", model: "ThinkPad T14 Gen 4", serial: "SN123459", warehouse: "Merkez Depo", location: "Genel Merkez", status: "Ready For Assignment", employeeId: "e-ipek", cost: 42500, history: [] },
  ];

  const assetTransitions = [
    { from: "In Stock", action: "Personel için ayır", to: "Reserved", role: "Sistem Destek Uzmanı" },
    { from: "Reserved", action: "Depo hazırlığı tamamla", to: "In Transfer", role: "Depo Sorumlusu" },
    { from: "In Transfer", action: "Teslim al", to: "Ready For Assignment", role: "Sistem Destek Uzmanı" },
    { from: "Ready For Assignment", action: "Zimmet oluştur", to: "Assigned", role: "Sistem Destek Uzmanı" },
    { from: "Assigned", action: "İade al", to: "Returned", role: "Sistem Destek Uzmanı" },
    { from: "Returned", action: "Yeniden kullanıma uygun", to: "Ready For Reassignment", role: "Sistem Destek Uzmanı" },
    { from: "Returned", action: "Bakıma gönder", to: "Maintenance", role: "Sistem Destek Uzmanı" },
    { from: "Returned", action: "Hurdaya ayır", to: "Retired", role: "Sistem Destek Uzmanı" },
    { from: "Assigned", action: "Kayıp bildir", to: "Lost", role: "Sistem Destek Uzmanı" },
    { from: "Assigned", action: "Çalıntı bildir", to: "Stolen", role: "Sistem Destek Uzmanı" },
    { from: "Maintenance", action: "Bakım tamamlandı", to: "Ready For Assignment", role: "Sistem Destek Uzmanı" },
    { from: "Maintenance", action: "Kullanılamaz", to: "Retired", role: "Sistem Destek Uzmanı" },
    { from: "Ready For Reassignment", action: "Yeni kullanıcıya zimmetle", to: "Assigned", role: "Sistem Destek Uzmanı" },
  ];

  const approvalRules = [
    { id: "ar-001", name: "Standart dışı ekipman — CO / CEO", process: "Standart dışı ekipman talepleri", active: true, levels: ["CO / CEO Onayı"], slaDays: 3, criteria: "Paket dışı ürün veya alternatif ürün paket dışında ise", example: "MacBook, 2. monitör, dock" },
    { id: "ar-002", name: "Cihaz değişimi — paket dışı", process: "Cihaz değişim işlemleri", active: true, levels: ["CO / CEO Onayı"], slaDays: 3, criteria: "Yeni cihaz title paketinde yoksa", example: "Software Developer → MacBook Pro" },
    { id: "ar-003", name: "Monitör tutar kademesi", process: "Yeni zimmet oluşturma", active: true, levels: ["Yönetici Onayı", "Direktör Onayı"], slaDays: 3, criteria: "Ürün grubu = Monitör · tutar bazlı", example: "0–50.000 TL onaysız · 50.000–150.000 TL yönetici · 150.000 TL üzeri yönetici + direktör" },
    { id: "ar-004", name: "Hurdaya ayırma", process: "Hurdaya ayırma işlemleri", active: true, levels: ["Sistem Destek Uzmanı", "Yönetici Onayı"], slaDays: 2, criteria: "Asset durumu Returned → Retired", example: "Kullanılamaz / hurda seçimi" },
    { id: "ar-005", name: "Depolar arası transfer", process: "Depolar arası transfer işlemleri", active: false, levels: ["Depo Sorumlusu"], slaDays: 2, criteria: "Transfer tipi = depolar arası", example: "IT Deposu → Merkez Depo (onay pasif)" },
    { id: "ar-006", name: "Zimmet devri", process: "Zimmet devri işlemleri", active: false, levels: [], slaDays: 3, criteria: "Aynı lokasyon kuralı yeterli", example: "Onay kapalı — yalnızca lokasyon kontrolü" },
  ];

  const approvalProcesses = [
    "Yeni zimmet oluşturma", "Ek ekipman tahsisi", "Cihaz değişim işlemleri", "Zimmet devri işlemleri",
    "Asset iade işlemleri", "Depolar arası transfer işlemleri", "Lokasyon transfer işlemleri",
    "Sevk irsaliyesi oluşturma işlemleri", "Hurdaya ayırma işlemleri", "Satın alma ihtiyacı oluşturan talepler",
    "Standart dışı ekipman talepleri", "Asset durum değişiklikleri",
  ];

  const permissions = {
    menus: [
      { name: "Özet", support: true, warehouse: true, ceo: true, hr: true, admin: true },
      { name: "Cihaz Zimmetleri", support: true, warehouse: true, ceo: true, hr: true, admin: true },
      { name: "İşe Başlangıç", support: true, warehouse: true, ceo: false, hr: true, admin: true },
      { name: "İşten Ayrılış", support: true, warehouse: false, ceo: false, hr: true, admin: true },
      { name: "Zimmet Devri", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "Cihaz Değişimi", support: true, warehouse: true, ceo: true, hr: false, admin: true },
      { name: "Assetler", support: true, warehouse: true, ceo: false, hr: false, admin: true },
      { name: "Depo Hazırlık", support: true, warehouse: true, ceo: false, hr: false, admin: true },
      { name: "Ekipman Paketleri", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "Onay Kuralları", support: false, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "Onaylarım", support: true, warehouse: false, ceo: true, hr: false, admin: true },
      { name: "Raporlar", support: true, warehouse: true, ceo: true, hr: true, admin: true },
    ],
    buttons: [
      { name: "Talep oluştur (İK)", support: false, warehouse: false, ceo: false, hr: true, admin: true },
      { name: "Depo sürecine gönder", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "CO / CEO onayına gönder", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "Onayla / Reddet", support: false, warehouse: false, ceo: true, hr: false, admin: true },
      { name: "Seri Seç", support: false, warehouse: true, ceo: false, hr: false, admin: true },
      { name: "Sevk İrsaliyesi Oluştur", support: false, warehouse: true, ceo: false, hr: false, admin: true },
      { name: "Zimmet Formu Oluştur", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "İade Tamamla", support: true, warehouse: false, ceo: false, hr: false, admin: true },
      { name: "Talebi iptal et", support: true, warehouse: false, ceo: false, hr: false, admin: true },
    ],
  };

  const auditLogs = [
    { id: "al-001", t: "2026-08-19 15:02", no: "IB-2026-0016", process: "İşe Başlangıç", step: "CO / CEO Onayı", who: "Sistem", result: "Hatırlatma", note: "1. iş günü hatırlatması · Selim Aras", from: "Onay Bekliyor", to: "Onay Bekliyor" },
    { id: "al-002", t: "2026-08-19 10:05", no: "DV-2026-0011", process: "Zimmet Devri", step: "Lokasyon kontrolü", who: "Ayşe Demir", result: "Devam", note: "Aynı lokasyon — Genel Merkez", from: "—", to: "Yeni Kullanıcı Bekleniyor" },
    { id: "al-003", t: "2026-08-19 09:41", no: "DG-2026-0009", process: "Cihaz Değişimi", step: "Paket kontrolü", who: "Sistem", result: "Onaya tabi", note: "MacBook Pro paket dışı", from: "Talep Oluşturuldu", to: "Talep Oluşturuldu" },
    { id: "al-004", t: "2026-08-19 09:13", no: "IB-2026-0018", process: "İşe Başlangıç", step: "Personel seçimi", who: "Mehmet Kaya", result: "Oluşturuldu", note: "Ahmet Yılmaz · LDAP", from: "—", to: "Sistem Destek Kontrolünde" },
    { id: "al-005", t: "2026-08-19 08:44", no: "IB-2026-0012", process: "İşe Başlangıç", step: "Seri seçimi", who: "Kemal Uçar", result: "Tamamlandı", note: "Logo ERP stok", from: "Depo Hazırlığında", to: "Depo Hazırlığında" },
    { id: "al-006", t: "2026-08-18 17:14", no: "IA-2026-0038", process: "İşten Ayrılış", step: "Asset durum", who: "Ayşe Demir", result: "Retired", note: "Kulaklık hurda · Logo hurda depo", from: "Returned", to: "Retired" },
    { id: "al-007", t: "2026-08-18 15:02", no: "IB-2026-0016", process: "İşe Başlangıç", step: "CO / CEO Onayı", who: "Ayşe Demir", result: "Onaya gönderildi", note: "Paket dışı monitör + dock", from: "Sistem Destek Kontrolünde", to: "Onay Bekliyor" },
    { id: "al-008", t: "2026-08-17 11:20", no: "IB-2026-0010", process: "İşe Başlangıç", step: "Sevk irsaliyesi", who: "Kemal Uçar", result: "Oluşturuldu", note: "Logo ERP · IRS-2026-1188", from: "Depo Hazırlığında", to: "Sevk Edildi" },
  ];

  const zimmetler = [
    { id: "zm-001", no: "ZM-2026-1042", jobId: "job-onb-001", type: "ise-baslangic", employeeId: "e-ahmet", equipment: "Laptop", name: "Apple MacBook Pro 14 M3", serial: "—", location: "Genel Merkez", status: "sistem-destek-kontrolunde" },
    { id: "zm-002", no: "ZM-2026-1043", jobId: "job-onb-001", type: "ise-baslangic", employeeId: "e-ahmet", equipment: "Monitör", name: "Dell P2723DE", serial: "—", location: "Genel Merkez", status: "sistem-destek-kontrolunde" },
    { id: "zm-003", no: "ZM-2026-1030", jobId: "job-onb-002", type: "ise-baslangic", employeeId: "e-elifd", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "—", location: "Genel Merkez", status: "ceo-onayi-bekliyor" },
    { id: "zm-004", no: "ZM-2026-1022", jobId: "job-onb-003", type: "ise-baslangic", employeeId: "e-burak", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "—", location: "Kartal", status: "depo-hazirliginda" },
    { id: "zm-005", no: "ZM-2026-1018", jobId: "job-onb-004", type: "ise-baslangic", employeeId: "e-merve", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "SN123456", location: "Genel Merkez", status: "seri-secildi" },
    { id: "zm-006", no: "ZM-2026-1004", jobId: "job-onb-005", type: "ise-baslangic", employeeId: "e-ceren", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "SN123457", location: "Genel Merkez", status: "merkeze-ulasti" },
    { id: "zm-007", no: "ZM-2026-0988", jobId: "job-onb-006", type: "ise-baslangic", employeeId: "e-hakan", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "SN123458", location: "Genel Merkez", status: "teknik-kontrol-bekliyor" },
    { id: "zm-008", no: "ZM-2026-0960", jobId: "job-onb-007", type: "ise-baslangic", employeeId: "e-ipek", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "SN123459", location: "Genel Merkez", status: "zimmet-formu-bekliyor" },
    { id: "zm-009", no: "ZM-2026-0208", jobId: "job-onb-008", type: "ise-baslangic", employeeId: "e-gokhan", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "LNV-T14-77001", location: "Genel Merkez", status: "tamamlandi" },
    { id: "zm-010", no: "ZM-2025-2218", jobId: "job-off-001", type: "isten-ayrilma", employeeId: "e-selin", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "LNV-T14-441902", location: "Kartal", status: "isten-ayrilis-bekliyor" },
    { id: "zm-011", no: "ZM-2025-2219", jobId: "job-off-001", type: "isten-ayrilma", employeeId: "e-selin", equipment: "Telefon", name: "Samsung Galaxy A54", serial: "SM-A546B-9912", location: "Kartal", status: "isten-ayrilis-bekliyor" },
    { id: "zm-012", no: "ZM-2026-0142", jobId: "job-off-002", type: "isten-ayrilma", employeeId: "e-can", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "HM4-14-771002", location: "Genel Merkez", status: "iade-kontrolunde" },
    { id: "zm-013", no: "ZM-2025-3001", jobId: "job-tr-001", type: "devir", employeeId: "e-baran", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "LNV-T14-300188", location: "Genel Merkez", status: "yeni-kullanici-bekliyor" },
    { id: "zm-014", no: "ZM-2025-3002", jobId: null, type: "ise-baslangic", employeeId: "e-baran", equipment: "Monitör", name: "Dell P2723DE", serial: "DELL-P27-300189", location: "Genel Merkez", status: "tamamlandi" },
    { id: "zm-015", no: "ZM-2026-0881", jobId: "job-ch-001", type: "degisim", employeeId: "e-mert", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "LNV-T14-552881", location: "Genel Merkez", status: "sistem-destek-kontrolunde" },
    { id: "zm-016", no: "ZM-2026-0790", jobId: "job-ch-002", type: "degisim", employeeId: "e-zeynep", equipment: "Keyboard", name: "Logitech MX Keys", serial: "LG-MXK-5519", location: "Genel Merkez", status: "depo-hazirliginda" },
    { id: "zm-017", no: "ZM-2026-0210", jobId: "job-onb-008", type: "ise-baslangic", employeeId: "e-gokhan", equipment: "Mouse", name: "Logitech MX Master 3S", serial: "LG-MX3S-77002", location: "Genel Merkez", status: "tamamlandi" },
    { id: "zm-018", no: "ZM-2025-1880", jobId: "job-off-003", type: "isten-ayrilma", employeeId: "e-nisa", equipment: "Laptop", name: "Lenovo ThinkPad T14 Gen 4", serial: "LNV-T14-18801", location: "Genel Merkez", status: "iade-tamamlandi" },
  ];

  const notifications = [
    { id: "n1", title: "Yeni Ekipman Teslim Alındı", body: "Ceren Uçar için hazırlanan 4 ekipman merkeze ulaştı.", t: "12 dk", unread: true, to: "#/ise-baslangic/job-onb-005", roles: ["support", "admin"] },
    { id: "n2", title: "Yeni Zimmet İadesi", body: "Selin Arslan'ın işten ayrılış işlemi nedeniyle 4 zimmetli ürünün iadesi bekleniyor.", t: "1 sa", unread: true, to: "#/isten-ayrilis/job-off-001", roles: ["support", "admin", "hr"] },
    { id: "n3", title: "CO / CEO onayı bekleniyor", body: "Elif Demir — paket dışı monitör ve dock.", t: "2 sa", unread: true, to: "#/onaylarim/job-onb-002", roles: ["ceo", "admin"] },
    { id: "n4", title: "Depo işlemi bekleniyor", body: "Burak Şen — satış paketi seri seçimi.", t: "3 sa", unread: true, to: "#/ise-baslangic/job-onb-003", roles: ["warehouse", "admin"] },
    { id: "n5", title: "Cihaz değişim talebi", body: "Mert Çelik — MacBook Pro (paket dışı).", t: "40 dk", unread: true, to: "#/cihaz-degisimi/job-ch-001", roles: ["support", "admin"] },
    { id: "n7", title: "SLA ihlali yaklaşıyor", body: "Elif Demir paket dışı talebi — CO / CEO onayı 3 iş günü SLA'sında 1. gün hatırlatması.", t: "10 dk", unread: true, to: "#/onaylarim", roles: ["ceo", "admin"] },
    { id: "n8", title: "İşe başlangıç talebi oluşturuldu", body: "Tuğçe Aydın taslak talep — cihaz teslim tarihi bekleniyor.", t: "20 dk", unread: true, to: "#/ise-baslangic/job-onb-009", roles: ["hr", "support", "admin"] },
  ];

  const activity = [
    { t: "10:05", text: "Baran Koç zimmeti için devir süreci başlatıldı." },
    { t: "09:40", text: "Mert Çelik cihaz değişim talebi oluşturdu (paket dışı)." },
    { t: "09:13", text: "Ahmet Yılmaz işe başlangıç zimmeti Sistem Destek kontrolüne düştü." },
    { t: "08:44", text: "Merve Kılıç paketinin tüm seri numaraları Logo'dan seçildi." },
    { t: "08:15", text: "Ceren Uçar ekipmanları merkeze ulaştı." },
    { t: "08:05", text: "İK, Selin Arslan işten ayrılış kaydını oluşturdu." },
  ];

  return {
    today,
    roles,
    employees,
    packages,
    logoCatalog,
    warehouses,
    jobs,
    zimmetler,
    assets,
    assetTransitions,
    approvalRules,
    approvalProcesses,
    permissions,
    auditLogs,
    notifications,
    activity,
  };
})();
